api:
  name: "mule-proc-ordermanagement"
  id: "16187789"
  version: "v1"
  
http:
  path: "/api/${api.version}/*"
  timeout: "5000" 
  port: "8080"
  private:
    port: "8091"
     
sys-salesforce:
  name: "mule-sys-salesforce"
  version: "v1"
  base_path: "/api/${sys-salesforce.version}"
  protocol: "HTTP"
  host: "mule-sys-salesforce-v1-sandbox.de-c1.cloudhub.io"
  port: "80"
