#%RAML 1.0 Library

types:
  customer:
    properties:
      firstName?: string
      lastName?: string
      address?: string
      orderId?: string
    example: !include examples/customer.json
      
  item:
    properties:
      id?: string
      category?: string
      quantity?: number
      size?: string
      orderId?: string
    example: !include examples/item.json

  order:
    properties:
      poNumber?: string
      signatureRequiredFlag?: boolean
      shipInstructions?: string
      giftWrapFlag?: boolean
      giftWrapMessage?: string
      currencyCode?: string
      subTotal?: number
      email?: string
    example: !include examples/order.json