#%RAML 1.0
title: Ordermanagement Process API
version: v1
mediaType: application/json

traits:
  client-id-policy: !include /exchange_modules/e8df9af0-19ba-4ede-8725-b905ab404dfe/clilent-id-policy/1.0.0/clilent-id-policy.raml

uses:
  datatypes: exchange_modules/e8df9af0-19ba-4ede-8725-b905ab404dfe/common-datatypes/1.0.2/common-datatypes.raml

/order:
  post:
    is: [client-id-policy]
    description: Create new order
    body:
      application/json:
        type: datatypes.order
        example: !include exchange_modules/e8df9af0-19ba-4ede-8725-b905ab404dfe/common-datatypes/1.0.2/examples/order.json